version: "3"
services:
  jupyter_anil:
    build: .
    volumes:
      - ./:/tmp/working
      - $PWD../ARC_DATAS_RESIZE:/ARC_DATAS_RESIZE
    working_dir: /tmp/working
    ports:
      - 8888:8888
    command: jupyter notebook --ip=0.0.0.0 --allow-root --no-browser